# Generated by Django 4.2.7 on 2023-11-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnX', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIdTable',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('UID', models.IntegerField()),
                ('topicid', models.IntegerField()),
            ],
            options={
                'db_table': 'chatidtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course', models.CharField(max_length=50)),
                ('level_info', models.CharField(max_length=50)),
                ('courseid', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'courseinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicid', models.BigAutoField(primary_key=True, serialize=False)),
                ('courseid', models.IntegerField()),
                ('content', models.TextField()),
                ('tname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCourseInfo',
            fields=[
                ('UID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usercourseinfo',
                'managed': False,
            },
        ),
    ]
