# Generated by Django 4.2.7 on 2023-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnX', '0003_chatidtable_courseinfo_topic_usercourseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('chat_q', models.TextField()),
                ('chat_A', models.TextField()),
                ('chat_notes', models.TextField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'chatinfo',
                'managed': False,
            },
        ),
    ]
