# Generated by Django 4.2.7 on 2023-11-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnX', '0004_chatinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatidtable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='chatinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='courseinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usercourseinfo',
            options={'managed': True},
        ),
    ]
